version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
