name: Git Conventions

on:
  pull_request:

jobs:
  ensure-linear-history:
    name: Ensure Linear Git History
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run Check
        uses: SE-UUlm/snowballr-ci/src/ensure-linear-history@v1.1.0
        with:
          target-branch: main