name: Quality Checks

on:
  push:
  pull_request:

env:
  node-version: ${{ vars.NODE_VERSION }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup/
        with:
          node_version: ${{ env.node-version }}

      - name: Run Biome
        shell: bash
        run: npm run lint

      - name: Lint Markdown Files
        shell: bash
        run: npm run lint:md