name: Lint and Publish Wiki

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  node-version: ${{ vars.NODE_VERSION }}

jobs:
  lint-md:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup/
        with:
          node_version: ${{ env.node-version }}

      - name: Lint Markdown
        shell: bash
        run: pnpm run lint:md

      - name: Get Branch Name
        id: get_branch_name
        shell: bash
        run: |
          BRANCH_NAME=""
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              BRANCH_NAME="${{ github.head_ref }}"
          else
              BRANCH_NAME="${{ github.ref_name }}"
          fi
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # To verify whether the links are up-to-date, we replace them with links to the current branch
      # In case we change the path of a file we link to in a Markdown file, this would result in a broken link on this branch
      # If we wouldn't check this, the broken link would only be noticed on the source branch
      - name: Replace GitHub URLs to the Source Branch with the Current Branch
        shell: bash
        run: node scripts/replace-github-urls.js ${{ github.repository }} main ${{ steps.get_branch_name.outputs.branch_name }} ${{ github.workspace }}/README.md ${{ github.workspace }}/wiki/

  publish-wiki:
    name: Publish Wiki
    if: github.ref_name == 'main' && github.ref_type == 'branch'
    runs-on: ubuntu-latest
    needs: lint-md
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Add auto-generated Hint to Wiki Markdown Files
        shell: bash
        run: bash scripts/add_auto_gen_wiki_hint.sh

      - name: Publish Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          path: ${{ github.workspace }}/wiki/
          strategy: "init"
